// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	scheme "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MCPBackendsGetter has a method to return a MCPBackendInterface.
// A group's client should implement this interface.
type MCPBackendsGetter interface {
	MCPBackends(namespace string) MCPBackendInterface
}

// MCPBackendInterface has methods to work with MCPBackend resources.
type MCPBackendInterface interface {
	Create(ctx context.Context, mCPBackend *apiv1beta1.MCPBackend, opts v1.CreateOptions) (*apiv1beta1.MCPBackend, error)
	Update(ctx context.Context, mCPBackend *apiv1beta1.MCPBackend, opts v1.UpdateOptions) (*apiv1beta1.MCPBackend, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, mCPBackend *apiv1beta1.MCPBackend, opts v1.UpdateOptions) (*apiv1beta1.MCPBackend, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1beta1.MCPBackend, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1beta1.MCPBackendList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1beta1.MCPBackend, err error)
	MCPBackendExpansion
}

// mCPBackends implements MCPBackendInterface
type mCPBackends struct {
	*gentype.ClientWithList[*apiv1beta1.MCPBackend, *apiv1beta1.MCPBackendList]
}

// newMCPBackends returns a MCPBackends
func newMCPBackends(c *AigatewayV1beta1Client, namespace string) *mCPBackends {
	return &mCPBackends{
		gentype.NewClientWithList[*apiv1beta1.MCPBackend, *apiv1beta1.MCPBackendList](
			"mcpbackends",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1beta1.MCPBackend { return &apiv1beta1.MCPBackend{} },
			func() *apiv1beta1.MCPBackendList { return &apiv1beta1.MCPBackendList{} },
		),
	}
}
