// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/typed/api/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeMCPBackends implements MCPBackendInterface
type fakeMCPBackends struct {
	*gentype.FakeClientWithList[*v1beta1.MCPBackend, *v1beta1.MCPBackendList]
	Fake *FakeAigatewayV1beta1
}

func newFakeMCPBackends(fake *FakeAigatewayV1beta1, namespace string) apiv1beta1.MCPBackendInterface {
	return &fakeMCPBackends{
		gentype.NewFakeClientWithList[*v1beta1.MCPBackend, *v1beta1.MCPBackendList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("mcpbackends"),
			v1beta1.SchemeGroupVersion.WithKind("MCPBackend"),
			func() *v1beta1.MCPBackend { return &v1beta1.MCPBackend{} },
			func() *v1beta1.MCPBackendList { return &v1beta1.MCPBackendList{} },
			func(dst, src *v1beta1.MCPBackendList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.MCPBackendList) []*v1beta1.MCPBackend { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.MCPBackendList, items []*v1beta1.MCPBackend) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
