// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MCPBackendLister helps list MCPBackends.
// All objects returned here must be treated as read-only.
type MCPBackendLister interface {
	// List lists all MCPBackends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1beta1.MCPBackend, err error)
	// MCPBackends returns an object that can list and get MCPBackends.
	MCPBackends(namespace string) MCPBackendNamespaceLister
	MCPBackendListerExpansion
}

// mCPBackendLister implements the MCPBackendLister interface.
type mCPBackendLister struct {
	listers.ResourceIndexer[*apiv1beta1.MCPBackend]
}

// NewMCPBackendLister returns a new MCPBackendLister.
func NewMCPBackendLister(indexer cache.Indexer) MCPBackendLister {
	return &mCPBackendLister{listers.New[*apiv1beta1.MCPBackend](indexer, apiv1beta1.Resource("mcpbackend"))}
}

// MCPBackends returns an object that can list and get MCPBackends.
func (s *mCPBackendLister) MCPBackends(namespace string) MCPBackendNamespaceLister {
	return mCPBackendNamespaceLister{listers.NewNamespaced[*apiv1beta1.MCPBackend](s.ResourceIndexer, namespace)}
}

// MCPBackendNamespaceLister helps list and get MCPBackends.
// All objects returned here must be treated as read-only.
type MCPBackendNamespaceLister interface {
	// List lists all MCPBackends in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1beta1.MCPBackend, err error)
	// Get retrieves the MCPBackend from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1beta1.MCPBackend, error)
	MCPBackendNamespaceListerExpansion
}

// mCPBackendNamespaceLister implements the MCPBackendNamespaceLister
// interface.
type mCPBackendNamespaceLister struct {
	listers.ResourceIndexer[*apiv1beta1.MCPBackend]
}
